### ISSUE TITLE
TypedArray support?

### ISSUE THREAD

**Issue by hax** [tc39/proposal-array-grouping#41]
Because of https://github.com/tc39/proposal-change-array-by-copy/issues/88#issuecomment-1164495562 I just realized TypedArray support [was removed](https://github.com/tc39/proposal-array-grouping/commit/84b3adc15d75fc1b863eaf0ba591bd9783be5d05). But that commit has no comments and I can't recall any related discussion in the plenary (I also did simple search in the notes and found nothing).

**Comment by jridgewell** [comment]
Notes on the decision are at https://github.com/tc39/notes/blob/167155eeb708d84e1758d99c88b15670f9b81f75/meetings/2021-10/oct-27.md#array-grouping-for-stage-2
